// <auto-generated />
namespace PlansApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedcheckinmessagetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcheckinmessagetable));
        
        string IMigrationMetadata.Id
        {
            get { return "201704032157551_added check in message table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
