// <auto-generated />
namespace PlansApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changednameofeventtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changednameofeventtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201704041459284_changed name of event table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
